trigger:
  - evaluation-scripts 

pool:
  vmImage: 'ubuntu-latest' 

variables:
  azureSubscription: '00c8eda5-6bb0-4c3c-b1d6-86e3b26ae2f9'
  functionAppName: 'dotnet-funcapp'
  resourceGroupName: 'TeamProject'
  environmentName: 'Production'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build --configuration Release
  displayName: 'Build the application'

- script: dotnet publish --configuration Release --output publish_output
  displayName: 'Publish function app'

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appType: 'functionApp'
    appName: $(functionAppName)
    package: '$(System.DefaultWorkingDirectory)/publish_output'
